

services:
  redis:
    image: redis:latest
    container_name: playlist_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server"]

  api:
    build: .
    container_name: playlist_api
    ports:
      - "8000:8000"
    volumes: # why? not needed
      - .:/app
    depends_on:
      - redis